version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./../frontend/dist:/usr/share/nginx/html:ro
      - /etc/letsencrypt/live/triada-kungfu.ru/:/etc/letsencrypt/live/triada-kungfu.ru/:ro
      - /etc/letsencrypt/archive/triada-kungfu.ru/:/etc/letsencrypt/archive/triada-kungfu.ru/:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - local_network
#  gateway:
#   build: ./../services/gateway
#    networks:
#      - local_network
#    depends_on:
#      - nginx
networks:
  local_network:
    driver: bridge